config/routes.rb
Rails.application.routes.draw do
  get 'comments' => 'comments#index', as: :comments

  post 'products/:product_id/comments' => 'comments#create', as: :product_comments

  resources :products

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products, :dependent => :delete_all

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
  
  validates :comment, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments, :dependent => :delete_all
  belongs_to :category
  
  validates :name, :description, :price, presence: true
  validates :name, length: { in:2..32 }, format: { with: /[A-Za-z]/ }, uniqueness: { case_sensitive: false }
  validates :description, format: { with: /[A-Za-z]/ }
  validates :price, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product, only: [:create]
  def index
    @comments = Comment.all.order('created_at desc')
  end

  def create
    @comment = @product.comments.build(comment_params)
    if @comment.save
      redirect_to product_path(params[:product_id].to_i)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to product_path(@product)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :delete]
  before_action :set_categories, only: [:new, :edit]
  before_action :set_prod_comments, only: [:show]

  def index
    @products = Product.all.order('created_at desc')
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      flash[:errors] = product.errors.full_messages
      render :new
    end
  end

  def show
    @comment = @product.comments.build
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      flash[:errors] = @product.errors.full_messages
      render :edit
    end
  end

  def delete
    @product.destroy
    redirect_to products_path
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end
  def set_categories
    @categories = Category.all
  end
  def set_prod_comments
    @prod_comments = Product.find(params[:id]).comments.order('created_at desc')
  end
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_comment.html.erb
<tr>
  <td><%= comment.comment %></td>
  <td><%= comment.product.name %></td>
</tr>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<% content_for :title do %>
  All comments
<% end %>

<h1>All Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
    </tr>
  </thead>
  <tbody>
    <%= render @comments %>
  </tbody>
</table>

<%= link_to 'Back', products_path %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |p| %>
  <%= p.label :category_id,"Category:" %>
  <%= p.select :category_id, options_from_collection_for_select(@categories, 'id', 'name', @product.category_id)  %><br>
  <%= p.label :name, 'Name:' %>
  <%= p.text_field :name %><br>
  <%= p.label :description, 'Description:' %>
  <%= p.text_area :description %><br>
  <%= p.label :price, 'Price:' %>
  <%= p.number_field :price, min: 0.01, step: 0.01 %><br>
  <%= p.submit %>
<% end %>

app/views/products/_prod_comment.html.erb
<% @prod_comments.each do |comment| %>
  <p class="comments">"<%= comment.comment %>" - <%= comment.created_at.strftime('%m/%d/%Y') %></p>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td>$<%= number_with_precision product.price, precision: 2 %></td>
  <td><%= product.category.name %></td>
  <td><%= link_to 'Show', product_path(product) %> | <%= link_to 'Edit', edit_product_path(product) %> | <%= link_to 'Delete', product_path(product), method: :delete %></td>
</tr>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<% content_for :title do %>
  Edit product <%= @product.id %>
<% end %>

<h1>Editing product (<%= @product.name %>)</h1>

<% if !flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
  <p class="errors"><%= error %></p>
  <% end %>
<% end %>

<%= render partial: 'form' %>

<%= link_to 'Show', product_path(@product) %> | <%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% content_for :title do %>
  All the products
<% end %>

<h1>Listing products</h1>
<button><%= link_to 'All comments', comments_path %></button>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @products %>
  </tbody>
</table>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<% content_for :title do %>
  Add a New Product
<% end %>

<h1>New product</h1>

<% if !flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
  <p class="errors"><%= error %></p>
  <% end %>
<% end %>

<%= render partial: 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% content_for :title do %>
  Product <%= @product.id %> Info
<% end %>

<h1>Showing information for Product <%= @product.id %></h1>

<p>Name: <%= @product.name %></p>
<p>Description: <%= @product.description %></p>
<p>Price: $<%= number_with_precision @product.price, precision: 2 %></p>
<p>Category: <%= @product.category.name %></p>

<%= link_to 'Edit', edit_product_path(@product) %> | <%= link_to 'Back', products_path %>

<h3>Comment:</h3>

<% if !flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
  <p class="errors"><%= error %></p>
  <% end %>
<% end %>

<%= form_for([@product, @comment]) do |c| %>
  <%= tag(:input, type: "hidden", name: 'product_id', value: @product.id) %>
  <%= c.text_area :comment %>
  <%= c.submit %>
<% end %>

<%= render partial: 'prod_comment' %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>